import React from 'react';
import { Booking } from '../types';
import { Calendar } from 'lucide-react';

interface DailySchedulePrintProps {
  roomName: string;
  dateStr: string;
  bookings: Booking[];
}

export const DailySchedulePrint = React.forwardRef<HTMLDivElement, DailySchedulePrintProps>((props, ref) => {
  const { roomName, dateStr, bookings } = props;

  // Ensure bookings are sorted by time
  const sortedBookings = [...bookings].sort((a, b) => a.startTime - b.startTime);

  return (
    <div ref={ref} className="w-full h-full bg-white text-black p-8 font-sans">
      {/* Header */}
      <div className="flex justify-between items-end border-b-4 border-black pb-4 mb-8">
        <div>
          <h1 className="text-4xl font-bold uppercase tracking-wider mb-2">Room Schedule</h1>
          <h2 className="text-2xl font-semibold text-gray-800 flex items-center gap-2">
            {roomName}
          </h2>
        </div>
        <div className="text-right">
          <div className="flex items-center justify-end gap-2 text-xl font-bold mb-1">
             <Calendar className="w-6 h-6" /> {dateStr}
          </div>
          <p className="text-gray-500 text-sm font-medium uppercase tracking-widest">RoomSync Organization</p>
        </div>
      </div>

      {/* Content */}
      {sortedBookings.length === 0 ? (
        <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed border-gray-300 rounded-xl bg-gray-50">
          <p className="text-3xl font-bold text-gray-400">No Meetings Scheduled Today</p>
          <p className="text-xl text-gray-400 mt-2">This room is available for walk-ins.</p>
        </div>
      ) : (
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-black text-white">
              <th className="py-4 px-6 text-left text-xl font-bold w-1/4">Time</th>
              <th className="py-4 px-6 text-left text-xl font-bold w-2/4">Meeting Details</th>
              <th className="py-4 px-6 text-left text-xl font-bold w-1/4">Organizer / Dept</th>
            </tr>
          </thead>
          <tbody className="divide-y-2 divide-gray-200">
            {sortedBookings.map((bk) => {
              const start = new Date(bk.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
              const end = new Date(bk.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

              return (
                <tr key={bk.id} className="break-inside-avoid">
                  <td className="py-6 px-6 align-top">
                    <div className="text-2xl font-bold">{start}</div>
                    <div className="text-lg text-gray-600">- {end}</div>
                  </td>
                  <td className="py-6 px-6 align-top">
                    <div className="text-2xl font-bold mb-1">{bk.purpose}</div>
                    {bk.pax && (
                        <span className="inline-block bg-gray-100 px-2 py-1 rounded text-sm font-semibold border border-gray-300">
                            {bk.pax} Attendees
                        </span>
                    )}
                  </td>
                  <td className="py-6 px-6 align-top">
                    <div className="text-xl font-semibold">{bk.unit || 'General'}</div>
                    <div className="text-base text-gray-600 mt-1">{bk.userEmail}</div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}

      {/* Footer */}
      <div className="fixed bottom-8 left-8 right-8 text-center border-t border-gray-300 pt-4">
        <p className="text-sm text-gray-500">Generated by RoomSync Admin System • Please vacate the room 5 minutes before the next slot.</p>
      </div>
    </div>
  );
});

DailySchedulePrint.displayName = 'DailySchedulePrint'; // Required for debugging
